#!/bin/bash
#clear

#DATABASELOCATION=/tmp/$USER"_db"
DATABASELOCATION="/tmp/nstoik1_db"

echo "--Starting Program--"

mkdir -p $DATABASELOCATION

cd bin/
CLASSPATH=$CLASSPATH:.:/usr/share/java/db.jar:.
export CLASSPATH
LD_LIBRARY_PATH=/oracle/lib
export LD_LIBRARY_PATH

#javac MainMenu.java
java MainMenu $1

#rm -rf $DATABASELOCATION

echo "--Program Execution Finished"



