#!/bin/bash
#clear

DATABASELOCATION="/tmp/nstoik1_db"

echo "--Starting Program--"

mkdir -p $DATABASELOCATION


CLASSPATH=$CLASSPATH:.:/usr/share/java/db.jar:.
export CLASSPATH
LD_LIBRARY_PATH=/oracle/lib
export LD_LIBRARY_PATH

echo "Compiling..."

javac -d bin -sourcepath src src/*.java
cd bin/
java MainMenu $1

#rm -rf $DATABASELOCATION

echo "--Program Execution Finished"



